"""Adapter of EnvFilesPort: the ``.env`` files the tool writes, and each service's own ``.env.example``."""

from __future__ import annotations

from pathlib import Path

from application.ports.outbound.env_files_port import EnvFilesPort
from domain.entities.host import Host
from domain.rules.dotenv import render_value

GENERATED_MARK = "# Generated by oblivion"  # first line of every .env this tool writes; the git adapter relies on it
GENERATED_HEADER = GENERATED_MARK + " for machine {machine}. Do not edit: change the files under config/.\n"


def render(values: dict[str, str], machine: str) -> str:
    return GENERATED_HEADER.format(machine=machine) + "".join(f"{k}={render_value(v)}\n" for k, v in sorted(values.items()))


class DotenvFiles(EnvFilesPort):
    def read_example(self, host: Host, name: str) -> str | None:
        example = host.service_dir(name) / ".env.example"
        return example.read_text(encoding="utf-8") if example.exists() else None

    def target(self, host: Host, name: str) -> Path:
        if host.services[name].runtime == "docker":
            return host.workdir / "env" / f"{name}.env"
        return host.service_dir(name) / ".env"

    def write(self, host: Host, name: str, values: dict[str, str]) -> Path:
        target = self.target(host, name)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(values, host.name), encoding="utf-8")
        try:
            target.chmod(0o600)  # it holds the API keys: readable by this user only (no effect on Windows)
        except OSError:
            pass
        return target
