#!/usr/bin/env python3
"""Launch the whole OBLIVION application on this machine (Windows, Linux or Raspberry Pi).

    python launch.py                 first run: deploys, starts, shows status
                                     later runs: updates to the newest code of the branch, restarts, shows status
    python launch.py stop            stop everything
    python launch.py status          state, code version and health of every service
    python launch.py logs [service]  last log lines (default: brain)

Options:  --branch REF   branch/tag/commit for every service (default: feature_ai_claude)
          --machine NAME which machine of robot.toml this is (only needed when it describes several)
          --stt local    use local Whisper instead of the OpenAI API (no key needed, big install; without a robot.toml)
          --no-update    start what is installed, do not fetch new code
          --console M    what each service window prints (Windows): stream (default, errors + stream events),
                         errors (errors only) or all. The log files always keep everything.
          --system-deps  Linux/Pi: apt-get install the system packages the services need (uses sudo)
          --dry-run      print every command, change nothing

It only needs Python 3.11+ and git. WITH a robot.toml (the single file of truth: layout, settings and keys) it deploys that
machine and creates nothing. WITHOUT one it creates hosts/local.toml and secrets/local.env (git-ignored) on the first run.
For several machines use oblivion.py, one `--host <machine>` per machine (see README.md).
"""

from __future__ import annotations

import argparse
import getpass
import os
import sys
from pathlib import Path

if sys.version_info < (3, 11):
    sys.exit("launch.py needs Python 3.11 or newer (found %d.%d)" % sys.version_info[:2])

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from oblivion.config import DeployError, apply_branch_overrides, load_host, load_registry, load_topology  # noqa: E402
from oblivion.envfile import is_secret  # noqa: E402
from oblivion.manager import Manager, Options  # noqa: E402
from oblivion.shell import Shell  # noqa: E402

DEFAULT_BRANCH = "feature_ai_claude"
HOST_NAME = "local"
HOST_FILE = ROOT / "hosts" / f"{HOST_NAME}.toml"
ROBOT_FILE = ROOT / "robot.toml"  # when it exists it is THE configuration: HOST_FILE and SECRETS_FILE are not used
SECRETS_FILE = ROOT / "secrets" / f"{HOST_NAME}.env"
# Everything the catalogue knows: the services to run, and ai-agent's LLM provider keys (which launch.py copies from the
# environment into the machine env file). Nothing about them is repeated here.
REGISTRY = load_registry(ROOT / "services.toml")
SERVICES = tuple(REGISTRY.services)
AI_AGENT_KEYS = tuple(key for key in REGISTRY.services["ai-agent"].require_any if is_secret(key))


def robot_machine(args: argparse.Namespace) -> str | None:
    """The machine of robot.toml this launch is for; None when there is no robot.toml (the generated host file is used)."""
    wanted = getattr(args, "machine", None)
    if not ROBOT_FILE.exists():
        if wanted:
            raise DeployError(f"--machine {wanted} needs a robot.toml (copy robot.example.toml to {_shown(ROBOT_FILE)})")
        return None
    machines = list(load_topology(ROBOT_FILE, REGISTRY).machines)
    if wanted:
        if wanted not in machines:
            raise DeployError(f"machine {wanted!r} is not in robot.toml (has: {', '.join(machines)})")
        return wanted
    if len(machines) == 1:
        return machines[0]
    raise DeployError(
        f"robot.toml describes {len(machines)} machines ({', '.join(machines)}): say which one this is, "
        f"e.g.  python launch.py --machine {machines[0]}"
    )


def _shown(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def host_file_text(branch: str, stt_engine: str) -> str:
    stt_env = '\n[services.stt.env]\nSTT_ENGINE = "local"\n' if stt_engine == "local" else ""
    services = "\n".join(f"[services.{name}]" for name in SERVICES if name != "stt")
    return (
        "# Generated by launch.py. Edit freely: launch.py never overwrites an existing file.\n"
        "# Every service runs on this machine, bound to 127.0.0.1; Brain reaches the others there. Ports, URLs and the\n"
        "# public LLM endpoints come from services.toml; keys and settings go in the env file below.\n"
        f'[host]\nname = "{HOST_NAME}"\nenv_file = "secrets/{HOST_NAME}.env"\n\n[defaults]\nbranch = "{branch}"\n\n'
        f"{services}\n[services.stt]{stt_env}"
    )


def read_secret_key(path: Path, key: str) -> str:
    if not path.exists():
        return ""
    for line in path.read_text(encoding="utf-8").splitlines():
        name, _, value = line.partition("=")
        if name.strip() == key:
            return value.strip()
    return ""


def ensure_files(branch: str, stt_engine: str, dry_run: bool, interactive: bool) -> list[str]:
    """Create hosts/local.toml and secrets/local.env when missing. Returns notes for the operator."""
    notes: list[str] = []
    if not HOST_FILE.exists():
        notes.append(f"created {_shown(HOST_FILE)}")
        HOST_FILE.parent.mkdir(exist_ok=True)  # also in a dry run: it is a git-ignored config file
        HOST_FILE.write_text(host_file_text(branch, stt_engine), encoding="utf-8")
    needs_key = stt_engine != "local" and "STT_ENGINE = \"local\"" not in (
        HOST_FILE.read_text(encoding="utf-8") if HOST_FILE.exists() else ""
    )
    if needs_key and not read_secret_key(SECRETS_FILE, "STT__OPENAI_API_KEY"):
        key = os.environ.get("OPENAI_API_KEY", "").strip()
        if not key and interactive and not dry_run:
            key = getpass.getpass("OpenAI API key for speech-to-text (input hidden, stored only in secrets/local.env): ").strip()
        if not key and not dry_run:
            raise DeployError(
                "STT needs an OpenAI API key. Set the OPENAI_API_KEY environment variable and run again, "
                f"or put STT__OPENAI_API_KEY=... in {_shown(SECRETS_FILE)}, or run with --stt local"
            )
        if key and not dry_run:
            SECRETS_FILE.parent.mkdir(exist_ok=True)
            with SECRETS_FILE.open("a", encoding="utf-8") as handle:
                handle.write(f"STT__OPENAI_API_KEY={key}\n")
            try:
                SECRETS_FILE.chmod(0o600)
            except OSError:
                pass
            notes.append(f"stored the key in {_shown(SECRETS_FILE)} (git-ignored)")
    if not dry_run:
        stored = [
            key for key in AI_AGENT_KEYS
            if os.environ.get(key, "").strip() and not read_secret_key(SECRETS_FILE, f"AI_AGENT__{key}")
        ]
        if stored:
            SECRETS_FILE.parent.mkdir(exist_ok=True)
            with SECRETS_FILE.open("a", encoding="utf-8") as handle:
                for key in stored:
                    handle.write(f"AI_AGENT__{key}={os.environ[key].strip()}\n")
            try:
                SECRETS_FILE.chmod(0o600)
            except OSError:
                pass
            notes.append(f"copied {', '.join(stored)} from the environment into {_shown(SECRETS_FILE)} for ai-agent (git-ignored)")
        if not any(read_secret_key(SECRETS_FILE, f"AI_AGENT__{key}") for key in AI_AGENT_KEYS):
            notes.append(
                "warning: no LLM provider key for ai-agent: export GROQ_API_KEY / GOOGLE_API_KEY and run again, "
                f"or add AI_AGENT__GROQ_API_KEY=... to {_shown(SECRETS_FILE)}. Without one ai-agent is not available"
            )
    return notes


def build_manager(args: argparse.Namespace) -> Manager:
    registry = load_registry(ROOT / "services.toml")
    machine = robot_machine(args)
    host = load_host(machine, registry, ROBOT_FILE) if machine else load_host(str(HOST_FILE), registry)
    if args.branch:
        host = apply_branch_overrides(host, [args.branch])
    options = Options(
        system_deps=getattr(args, "system_deps", False),
        health_timeout=getattr(args, "health_timeout", 180.0),
    )
    return Manager(Shell(dry_run=args.dry_run), host, registry, options)


def print_status(manager: Manager) -> int:
    rows = manager.status(None, False)
    width = max(len(r[0]) for r in rows)
    print()
    for name, state, detail in rows:
        print(f"  {name:<{width}}  {state:<10} {detail}")
    return 0 if all(r[1] == "running" for r in rows) else 1


def cmd_up(args: argparse.Namespace) -> int:
    interactive = sys.stdin.isatty()
    os.environ["OBLIVION_CONSOLE_FILTER"] = args.console  # read by oblivion/tee.py in each service window
    machine = robot_machine(args)
    if machine:
        if args.stt == "local":
            raise DeployError('--stt local only shapes the generated host file: with robot.toml set STT_ENGINE = "local" under [env.stt]')
        print(f"Using {_shown(ROBOT_FILE)}: machine {machine!r} (settings and keys come from that file)")
    else:
        for note in ensure_files(args.branch or DEFAULT_BRANCH, args.stt, args.dry_run, interactive):
            print(note)
    manager = build_manager(args)
    if not args.dry_run:
        errors, warnings = manager.validate(None)
        for warning in warnings:
            print(f"warning: {warning}")
        if errors:
            raise DeployError("cannot launch:\n  " + "\n  ".join(errors))

    installed = all(manager.state.get(name).get("commit") for name in manager.host.services)
    if installed and args.no_update:
        print("Starting the installed services (--no-update)")
        failures = manager.start(None)
    elif installed:
        print("Updating to the newest code of the branch and restarting")
        failures = manager.update(None)  # also starts every service, healthy or rolled back
    else:
        print("First run: fetching code and installing dependencies (a few minutes)")
        failures = manager.deploy(None)

    if not args.dry_run:
        print_status(manager)
    if failures:
        print("\nFAILED:")
        for failure in failures:
            print(f"  - {failure}")
        print("\nSee the reason with:  python launch.py logs <service>")
        return 1
    if not args.dry_run:
        print(
            "\nAll services are up. Brain now opens the voice pipeline: use HEADPHONES, say a sentence and pause "
            "about two seconds; you should hear it repeated.\n"
            "  python launch.py logs      Brain's log (which hop is active)\n"
            "  python launch.py stop      stop everything"
        )
    return 0


def cmd_stop(args: argparse.Namespace) -> int:
    build_manager(args).stop(None)
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    return print_status(build_manager(args))


def cmd_logs(args: argparse.Namespace) -> int:
    manager = build_manager(args)
    name = args.service
    if name not in manager.host.services:
        raise DeployError(f"unknown service {name!r}; known: {', '.join(manager.host.services)}")
    path = manager.host.log_file(name)
    print(f"== {name} ({path})")
    if path.exists():
        print("\n".join(path.read_text(errors="replace").splitlines()[-args.lines:]))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="launch.py", description=(__doc__ or "").split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--dry-run", action="store_true", help="print every command, change nothing")
    sub = parser.add_subparsers(dest="command")
    dry = argparse.ArgumentParser(add_help=False)
    dry.add_argument("--dry-run", action="store_true", default=argparse.SUPPRESS, help=argparse.SUPPRESS)
    dry.add_argument("--machine", metavar="NAME", default=argparse.SUPPRESS, help="the machine of robot.toml this is")
    up = sub.add_parser("up", parents=[dry], help="deploy or update, start everything (default)")
    up.add_argument("--branch", metavar="REF", help=f"branch, tag or commit for every service (default: {DEFAULT_BRANCH})")
    up.add_argument("--stt", choices=["openai", "local"], default="openai", help="speech-to-text engine")
    up.add_argument("--no-update", action="store_true", help="start what is installed; do not fetch new code")
    up.add_argument(
        "--console", choices=["stream", "errors", "all"], default=os.environ.get("OBLIVION_CONSOLE_FILTER", "stream"),
        help="what each service window prints (Windows): errors + stream events (default), errors only, or everything",
    )
    up.add_argument("--system-deps", action="store_true", help="Linux/Pi: apt-get install the packages services need")
    up.add_argument("--health-timeout", type=float, default=180.0, metavar="SECONDS")
    sub.add_parser("stop", parents=[dry], help="stop everything")
    sub.add_parser("status", parents=[dry], help="state and health of every service")
    logs = sub.add_parser("logs", parents=[dry], help="print the last log lines of a service")
    logs.add_argument("service", nargs="?", default="brain")
    logs.add_argument("--lines", "-n", type=int, default=60)
    return parser


COMMANDS = ("up", "stop", "status", "logs")


def normalize(argv: list[str]) -> list[str]:
    """``launch.py --branch X`` (no command) means ``launch.py up --branch X``."""
    if any(arg in COMMANDS for arg in argv) or any(arg in ("-h", "--help") for arg in argv):
        return argv
    dry_run = [arg for arg in argv if arg == "--dry-run"]
    return [*dry_run, "up", *[arg for arg in argv if arg != "--dry-run"]]


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(normalize(sys.argv[1:] if argv is None else argv))
    args.branch = getattr(args, "branch", None)
    try:
        if not HOST_FILE.exists() and not ROBOT_FILE.exists() and args.command in ("stop", "status", "logs"):
            raise DeployError("nothing deployed yet: run  python launch.py  first")
        return {"up": cmd_up, "stop": cmd_stop, "status": cmd_status, "logs": cmd_logs}[args.command](args)
    except DeployError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        return 130


if __name__ == "__main__":
    sys.exit(main())
