"""Deploy, branch switching, update and rollback against real git repositories and real processes."""

from __future__ import annotations

import json
import sys
import urllib.request
from pathlib import Path

import pytest
from conftest import FakeRemote, free_port, git, write_registry

from oblivion.config import DeployError, apply_branch_overrides, load_host, load_registry
from oblivion.manager import Manager, Options
from oblivion.shell import Shell


class Platform:
    def __init__(self, base: Path) -> None:
        self.base = base
        self.ports = {"producer": free_port(), "consumer": free_port()}
        self.remotes = {"producer": FakeRemote(base, "producer"), "consumer": FakeRemote(base, "consumer")}
        self.registry_path = write_registry(base, self.remotes, self.ports)
        self.workdir = base / "work"

    def host_file(self, extra: str = "") -> Path:
        path = self.base / "host.toml"
        path.write_text(
            f'[host]\nname = "t"\nos = "linux"\nworkdir = "{self.workdir.as_posix()}"\npython = "{Path(sys.executable).as_posix()}"\n'
            '[services.producer]\n[services.producer.env]\nT_MARK = "hello"\n[services.consumer]\n' + extra
        )
        return path

    def manager(self, overrides: list[str] | None = None, **options) -> Manager:
        registry = load_registry(self.registry_path)
        host = apply_branch_overrides(load_host(str(self.host_file()), registry), overrides or [])
        return Manager(Shell(echo=False), host, registry, Options(health_timeout=15, **options))

    def get(self, service: str, path: str) -> dict:
        with urllib.request.urlopen(f"http://127.0.0.1:{self.ports[service]}{path}", timeout=5) as response:
            return json.loads(response.read())


@pytest.fixture
def platform(tmp_path: Path):
    p = Platform(tmp_path)
    yield p
    try:
        p.manager().stop(None)
    except DeployError:
        pass


def test_deploy_installs_in_dependency_order_writes_env_and_starts_healthy(platform):
    manager = platform.manager()

    assert manager.select(None) == ["producer", "consumer"]  # what others consume comes first
    assert manager.deploy(None) == []

    assert platform.get("producer", "/version")["version"] == "v1"
    consumer_env = platform.get("consumer", "/version")["env"]
    assert consumer_env["PRODUCER_BASE_URL"] == f"http://127.0.0.1:{platform.ports['producer']}"
    producer_env = platform.get("producer", "/version")["env"]
    assert producer_env["T_MARK"] == "hello" and producer_env["T_DEFAULT"] == "from-example"

    env_file = (platform.workdir / "services" / "producer_microservice" / ".env").read_text()
    assert "Generated by oblivion" in env_file and f"SERVICE_PORT={platform.ports['producer']}" in env_file
    rows = {name: state for name, state, _ in manager.status(None, False)}
    assert rows == {"producer": "running", "consumer": "running"}
    assert manager.state.get("producer")["commit"] == git(platform.remotes["producer"].work, "rev-parse", "HEAD")


def test_a_test_branch_can_be_deployed_for_one_service_and_main_stays_for_the_rest(platform):
    platform.remotes["producer"].release("v2-test", branch="feature_test")

    manager = platform.manager(["producer=feature_test"])
    assert manager.deploy(None) == []

    assert platform.get("producer", "/version")["version"] == "v2-test"
    assert platform.get("consumer", "/version")["version"] == "v1"
    assert git(platform.workdir / "services" / "producer_microservice", "rev-parse", "--abbrev-ref", "HEAD") == "feature_test"

    # and back to main with one command
    assert platform.manager().update(None) == []
    assert platform.get("producer", "/version")["version"] == "v1"


def test_update_follows_new_commits_of_the_branch(platform):
    assert platform.manager().deploy(None) == []
    platform.remotes["consumer"].release("v2")

    assert platform.manager().update(None) == []

    assert platform.get("consumer", "/version")["version"] == "v2"
    assert platform.get("producer", "/version")["version"] == "v1"


def test_a_release_that_does_not_start_is_rolled_back_to_the_running_version(platform):
    assert platform.manager().deploy(None) == []
    platform.remotes["consumer"].release("broken")

    failures = platform.manager().update(["consumer"])

    assert failures and "consumer" in failures[0] and "not healthy" in failures[0]
    assert platform.get("consumer", "/version")["version"] == "v1"  # the old code is serving again
    assert platform.manager().status(["consumer"], False)[0][1] == "running"


def test_without_rollback_the_failed_release_is_left_for_inspection(platform):
    assert platform.manager().deploy(None) == []
    platform.remotes["consumer"].release("broken")

    failures = platform.manager(rollback=False).update(["consumer"])

    assert failures
    assert platform.manager().status(["consumer"], False)[0][1] == "stopped"
    log = (platform.workdir / "logs" / "consumer.log").read_text()
    assert "this release crashes on start" in log


def test_local_modifications_are_never_overwritten_without_force(platform):
    assert platform.manager().deploy(None) == []
    repo = platform.workdir / "services" / "producer_microservice"
    (repo / "main.py").write_text((repo / "main.py").read_text() + "\n# hotfix on the machine\n")
    platform.remotes["producer"].release("v2")

    failures = platform.manager().update(["producer"])
    assert failures and "local modifications" in failures[0]
    assert "hotfix on the machine" in (repo / "main.py").read_text()

    assert platform.manager(force=True).update(["producer"]) == []
    assert platform.get("producer", "/version")["version"] == "v2"


def test_an_unknown_branch_is_a_clear_error_and_changes_nothing(platform):
    assert platform.manager().deploy(None) == []

    failures = platform.manager(["producer=no_such_branch"]).update(["producer"])

    assert failures and "no_such_branch" in failures[0] and "not a branch, tag or commit" in failures[0]
    assert platform.get("producer", "/version")["version"] == "v1"


def test_a_tag_or_commit_can_be_deployed(platform):
    first = git(platform.remotes["producer"].work, "rev-parse", "HEAD")
    platform.remotes["producer"].release("v2")
    assert platform.manager([f"producer={first}"]).deploy(["producer"]) == []
    assert platform.get("producer", "/version")["version"] == "v1"


def test_dry_run_changes_nothing(platform):
    manager = platform.manager()
    manager.shell.dry_run = True

    assert manager.deploy(None) == []

    assert not platform.workdir.exists()


def test_stop_is_idempotent_and_frees_the_port(platform):
    manager = platform.manager()
    assert manager.deploy(None) == []
    manager.stop(None)
    manager.stop(None)
    assert [state for _, state, _ in manager.status(None, False)] == ["stopped", "stopped"]
    with pytest.raises(OSError):
        platform.get("producer", "/health")
