"""Environment variables: layered merge, secrets, validation and the generated ``.env``.

Layers, lowest to highest priority (a later layer overrides an earlier one):

1. ``defaults``  the service repo's own ``.env.example``
2. ``registry``  ``[services.<name>.env]`` in services.toml
3. ``computed``  SERVICE_HOST / SERVICE_PORT (or the service's own names) and the base URLs of the services it consumes
4. ``host``      ``[services.<name>.env]`` in the host file
5. ``secrets``   ``<SERVICE>__<KEY>=value`` lines of the machine's secrets file (never committed)
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from .config import Host, ServiceInstance

LAYERS = ("defaults", "registry", "computed", "host", "secrets")
_INLINE_COMMENT = re.compile(r"(^|\s)#.*$")
_SECRET_NAME =re.compile(r"KEY(?!WORDS)|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|GITHUB_PAT", re.IGNORECASE)
GENERATED_MARK = "# Generated by oblivion"  # first line of every .env this tool writes; gitops relies on it
GENERATED_HEADER = GENERATED_MARK + " for host {host}. Do not edit: change the host file or the secrets file.\n"


def parse_env(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        key, _, value = line.partition("=")
        values[key.strip()] = _value(value)
    return values


def _value(raw: str) -> str:
    """The value of ``KEY=<raw>``: quotes removed, and for unquoted values an inline ``# comment`` dropped.

    A ``#`` starts a comment only at the start or after whitespace (``abc#def`` is a value), like dotenv.
    """
    raw = raw.strip()
    if raw[:1] in ("'", '"'):
        closing = raw.find(raw[0], 1)
        if closing != -1:
            return raw[1:closing]  # whatever follows the closing quote is a comment
    return _INLINE_COMMENT.sub("", raw).strip()


def is_secret(key: str) -> bool:
    return bool(_SECRET_NAME.search(key))


def mask(key: str, value: str) -> str:
    return "********" if is_secret(key) and value else value


def render(values: dict[str, str], host_name: str) -> str:
    return GENERATED_HEADER.format(host=host_name) + "".join(f"{k}={v}\n" for k, v in sorted(values.items()))


def read_secrets(path: Path | None) -> dict[str, dict[str, str]]:
    """``SERVICE__KEY=value`` lines grouped by service (lower case)."""
    grouped: dict[str, dict[str, str]] = {}
    if path is None or not path.exists():
        return grouped
    for key, value in parse_env(path.read_text(encoding="utf-8")).items():
        service, sep, name = key.partition("__")
        if sep and name:
            grouped.setdefault(service.lower(), {})[name] = value
    return grouped


@dataclass
class ResolvedEnv:
    values: dict[str, str] = field(default_factory=dict)
    layer_of: dict[str, str] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def set(self, layer: str, key: str, value: str) -> None:
        self.values[key] = value
        self.layer_of[key] = layer


def service_url(host: Host, consumer: ServiceInstance, target: str) -> str | None:
    """Base URL the ``consumer`` must use to reach ``target`` from this machine."""
    if target in host.services:
        port = host.services[target].port
        # A container reaches services published on the host through the special host name.
        address = "host.docker.internal" if consumer.runtime == "docker" else "127.0.0.1"
        return f"http://{address}:{port}"
    return host.remote.get(target)


def resolve_env(host: Host, name: str, defaults_file: Path | None) -> ResolvedEnv:
    instance = host.services[name]
    spec = instance.spec
    resolved = ResolvedEnv()

    known: set[str] = set()
    documented = defaults_file is not None and defaults_file.exists()  # else: cannot tell typos
    if documented:
        for key, value in parse_env(defaults_file.read_text(encoding="utf-8")).items():
            resolved.set("defaults", key, value)
            known.add(key)
    for key, value in spec.env.items():
        resolved.set("registry", key, value)
        known.add(key)

    bind = "0.0.0.0" if instance.runtime == "docker" else host.bind
    resolved.set("computed", spec.host_var, bind)
    resolved.set("computed", spec.port_var, str(instance.port))
    for target, var in spec.consumes.items():
        url = service_url(host, instance, target)
        if url:
            resolved.set("computed", var, url)
            known.add(var)
    known.update({spec.host_var, spec.port_var, "SERVICE_NAME", "LOG_LEVEL", "APP_ENV"})

    for key, value in instance.env.items():
        resolved.set("host", key, value)
        if documented and key not in known:
            resolved.warnings.append(f"{name}: {key} is set in the host file but the service does not document it (typo?)")

    secrets = read_secrets(host.secrets).get(name.replace("-", "_"), {})
    for key, value in secrets.items():
        resolved.set("secrets", key, value)

    if spec.require_any and not any(resolved.values.get(key) for key in spec.require_any):
        hint = name.upper().replace("-", "_")
        resolved.warnings.append(
            f"{name}: none of {', '.join(spec.require_any)} is set, so it will report itself not available; "
            f"put a key in the secrets file as {hint}__<NAME>=..."
        )

    for rule in spec.require:
        if all(resolved.values.get(k) == v for k, v in rule.when.items()) and not resolved.values.get(rule.key):
            condition = ", ".join(f"{k}={v}" for k, v in rule.when.items())
            hint = f"{name.upper().replace('-', '_')}__{rule.key}"
            resolved.errors.append(
                f"{name}: {rule.key} is required" + (f" when {condition}" if condition else "")
                + f"; put {hint}=... in the secrets file"
            )
    return resolved
