"""Environment variables: layered merge, the robot file, the machine env file, validation and the generated ``.env``.

The robot file (``robot.toml``, git-ignored) is the single file of truth: the layout AND every setting and key.
``[env]`` holds a value once for every service that uses that variable (a log level, an OpenAI key both STT and ai-agent
need) and ``[env.<service>]`` one service's own. Every service runs on exactly one machine, so nothing is per machine.
A machine may add an optional, machine-local ``secrets/<machine>.env`` (``<SERVICE>__<NAME>=value`` and ``ALL__<NAME>``
lines) for keys that must not sit in the file every machine gets; its values win.

Layers, lowest to highest priority (a later layer overrides an earlier one):

1. ``defaults``       the service repo's own ``.env.example``
2. ``registry``       ``[services.<name>.env]`` in services.toml
3. ``computed``       SERVICE_HOST / SERVICE_PORT (or the service's own names) and the base URLs of the services it consumes
4. ``robot ALL``      ``[env]`` of the robot file, for every service that uses the variable
5. ``env file ALL``   ``ALL__<NAME>=value`` lines of the machine env file
6. ``host``           ``[services.<name>.env]`` in a host file
7. ``robot``          ``[env.<service>]`` of the robot file
8. ``env file``       ``<SERVICE>__<NAME>=value`` lines of the machine env file
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from collections.abc import Callable, Mapping
from fnmatch import fnmatchcase
from pathlib import Path

from .config import Host, ServiceInstance, ServiceSpec
from .envparse import parse_env, render_value

LAYER_ROBOT_ALL, LAYER_ROBOT = "robot ALL", "robot"
LAYER_ALL, LAYER_FILE = "env file ALL", "env file"
# TRACE_EXPORT_HEADERS is where a collector's Authorization header goes
_SECRET_NAME = re.compile(r"KEY(?!WORDS)|TOKEN|SECRET|PASSWORD|PASSWD|CREDENTIAL|GITHUB_PAT|HEADERS", re.IGNORECASE)
# Read by shared-logging in every service (see shared-logging/docs/logging.md), so never a "typo" in a host file
ALL_PREFIX = "ALL"  # ALL__<NAME> in the machine env file: one value for every service that uses that variable
# Tuning knobs whose defaults suit every deployment and that no service needs to see: accepted, never advertised.
TUNING_VARS = frozenset({
    "SERVICE_NAME", "VSCODE_ENV", "TRACE_EXPORT_TIMEOUT", "TRACE_EXPORT_BATCH_SIZE", "TRACE_EXPORT_FLUSH_INTERVAL",
    "TRACE_EXPORT_QUEUE_SIZE",
})
SHARED_LOGGING_VARS = frozenset({
    "SERVICE_NAME", "LOG_LEVEL", "LOG_FORMAT", "LOG_OUTPUT", "APP_ENV", "ENVIRONMENT", "VSCODE_ENV",
    *(f"TRACE_EXPORT_{s}" for s in ("ENABLED", "URL", "TIMEOUT", "BATCH_SIZE", "FLUSH_INTERVAL", "QUEUE_SIZE", "HEADERS", "ATTRIBUTES")),
})
GENERATED_MARK = "# Generated by oblivion"  # first line of every .env this tool writes; gitops relies on it
GENERATED_HEADER = GENERATED_MARK + " for host {host}. Do not edit: change the host file or the machine env file.\n"


def is_secret(key: str) -> bool:
    return bool(_SECRET_NAME.search(key))


def mask(key: str, value: str) -> str:
    return "********" if is_secret(key) and value else value


def render(values: dict[str, str], host_name: str) -> str:
    return GENERATED_HEADER.format(host=host_name) + "".join(f"{k}={render_value(v)}\n" for k, v in sorted(values.items()))


def service_prefix(name: str) -> str:
    """``ai-agent`` -> ``AI_AGENT``: how the machine env file names a service."""
    return name.upper().replace("-", "_")


def computed_variables(spec: ServiceSpec) -> set[str]:
    """Set by the deploy tool from the topology or the host file: bind address, port, URLs of the consumed services."""
    return {spec.host_var, spec.port_var, *spec.consumes.values()}


def _matches(key: str, patterns: tuple[str, ...]) -> bool:
    return any(fnmatchcase(key, pattern) for pattern in patterns)


def known_variables(spec: ServiceSpec, example: Path | None) -> tuple[Callable[[str], bool], bool]:
    """``(is_known, documented)``: whether a variable name is one the service uses, and whether its ``.env.example`` was seen.

    Knowledge comes from the catalogue (its presets, required keys and providers, the shared-logging names, what the tool
    computes, ``extra_env``, ``internal``) and, once the code is fetched, from the service's own ``.env.example``.
    """
    known = {
        *spec.env, *(rule.key for rule in spec.require), *spec.require_any, *computed_variables(spec), *SHARED_LOGGING_VARS,
    }
    documented = example is not None and example.exists()
    if documented:
        text = example.read_text(encoding="utf-8")
        known.update(parse_env(text))
        known.update(re.findall(r"^#\s?([A-Z][A-Z0-9_]{2,})=", text, re.M))  # commented-out variables are documented too

    def is_known(key: str) -> bool:
        return key in known or _matches(key, spec.extra_env) or _matches(key, spec.internal)

    return is_known, documented


def read_env_file(path: Path | None) -> dict[str, dict[str, str]]:
    """The machine env file's ``PREFIX__NAME=value`` lines grouped by prefix (upper case, ``ALL`` for shared ones)."""
    grouped: dict[str, dict[str, str]] = {}
    if path is None or not path.exists():
        return grouped
    for key, value in parse_env(path.read_text(encoding="utf-8")).items():
        prefix, sep, name = key.partition("__")
        if sep and name:
            grouped.setdefault(prefix.upper(), {})[name] = value
    return grouped


def check_env_file(host: Host, specs: Mapping[str, ServiceSpec], examples: Mapping[str, Path] | None = None) -> list[str]:
    """Warnings about lines of the machine env file that nothing reads. Needs no network and no clone.

    ``examples`` are the ``.env.example`` files of the services fetched on this machine; a variable can only be called
    unknown to every service when all of them were seen.
    """
    path = host.env_file
    if path is None:
        return []
    if not path.exists():
        return [f"the machine env file {path} does not exist, so no value is read from it"]
    examples = examples or {}
    checkers = {n: known_variables(spec, examples.get(n)) for n, spec in specs.items()}
    prefixes = {service_prefix(n) for n in specs}
    warnings: list[str] = []
    seen: dict[str, str] = {}
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key = line.removeprefix("export ").partition("=")[0].strip()
        where = f"{path.name} line {number}"
        prefix, sep, name = key.partition("__")
        if "=" not in line:
            warnings.append(f"{where}: {line!r} is not NAME=value and is ignored")
        elif not sep or not name:
            warnings.append(f"{where}: {key} has no SERVICE__ prefix, so no service reads it (write SERVICE__{key}=... or ALL__{key}=...)")
        elif prefix.upper() == ALL_PREFIX:
            if name == "SERVICE_NAME" or any(name in computed_variables(spec) for spec in specs.values()):
                warnings.append(f"{where}: {key} is ignored: it is different for every service or computed from the topology")
            elif not any(known(name) for known, _ in checkers.values()) and all(doc for _, doc in checkers.values()):
                warnings.append(f"{where}: {key}: no service uses {name}, so it is ignored (typo?)")
        elif prefix.upper() not in prefixes:
            warnings.append(f"{where}: {prefix!r} is not a service of the catalogue ({', '.join(sorted(prefixes))}), so {key} is ignored")
        value = line.partition("=")[2].strip()
        if seen.get(key):  # an empty earlier line is just the template's placeholder
            warnings.append(f"{where}: {key} is set twice; the later line wins")
        seen[key] = value
    return warnings


@dataclass
class ResolvedEnv:
    values: dict[str, str] = field(default_factory=dict)
    layer_of: dict[str, str] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)

    def set(self, layer: str, key: str, value: str) -> None:
        self.values[key] = value
        self.layer_of[key] = layer


def service_url(host: Host, consumer: ServiceInstance, target: str) -> str | None:
    """Base URL the ``consumer`` must use to reach ``target`` from this machine."""
    if target in host.services:
        port = host.services[target].port
        # A container reaches services published on the host through the special host name.
        address = "host.docker.internal" if consumer.runtime == "docker" else "127.0.0.1"
        return f"http://{address}:{port}"
    return host.remote.get(target)


def resolve_env(host: Host, name: str, defaults_file: Path | None) -> ResolvedEnv:
    instance = host.services[name]
    spec = instance.spec
    resolved = ResolvedEnv()

    is_known, documented = known_variables(spec, defaults_file)  # else: cannot tell typos
    if documented:
        for key, value in parse_env(defaults_file.read_text(encoding="utf-8")).items():
            resolved.set("defaults", key, value)
    for key, value in spec.env.items():
        resolved.set("registry", key, value)

    bind = "0.0.0.0" if instance.runtime == "docker" else host.bind
    resolved.set("computed", spec.host_var, bind)
    resolved.set("computed", spec.port_var, str(instance.port))
    for target, var in spec.consumes.items():
        url = service_url(host, instance, target)
        if url:
            resolved.set("computed", var, url)
    computed = computed_variables(spec)

    lines = read_env_file(host.env_file)
    robot = host.topology.name if host.topology else "robot.toml"

    def how_to_set(key: str) -> str:
        if host.machine:
            return f'put {key} = "..." under [env.{name}] (or [env] for every service that uses it) in {robot}'
        return f"put {service_prefix(name)}__{key}=... (or ALL__{key}=...) in the machine env file"

    def applies_to_all(key: str) -> bool:
        return key != "SERVICE_NAME" and key not in computed and is_known(key)  # only the services that use the variable

    for key, value in host.config_all.items():
        if applies_to_all(key):
            resolved.set(LAYER_ROBOT_ALL, key, value)
    for key, value in lines.get(ALL_PREFIX, {}).items():
        if applies_to_all(key):
            resolved.set(LAYER_ALL, key, value)

    for key, value in instance.env.items():
        resolved.set("host", key, value)
        if documented and not is_known(key):
            resolved.warnings.append(f"{name}: {key} is set in the host file but the service does not document it (typo?)")

    def apply_own(items: dict[str, str], layer: str, source: str) -> None:
        for key, value in items.items():
            resolved.set(layer, key, value)
            if key in computed:
                resolved.warnings.append(
                    f"{name}: {key} is computed from {robot if host.machine else 'the host file'} (address, port, URLs of the other services); the value in {source} "
                    "wins here, but the other services still use the computed one, so they will not find each other"
                )
            elif documented and not is_known(key):
                resolved.warnings.append(f"{name}: {key} is set in {source} but the service does not document it (typo?)")

    apply_own(host.config.get(name, {}), LAYER_ROBOT, robot)
    apply_own(lines.get(service_prefix(name), {}), LAYER_FILE, "the machine env file")

    if spec.require_any and not any(resolved.values.get(key) for key in spec.require_any):
        resolved.warnings.append(
            f"{name}: none of {', '.join(spec.require_any)} is set, so it will report itself not available; "
            f"{how_to_set('GROQ_API_KEY')}"
        )

    for key, value in resolved.values.items():
        if "${" in value:  # python-dotenv expands ${NAME} in every value, quoted or not, and offers no way to stop it
            resolved.errors.append(
                f"{name}: {key} contains '${{', which python-dotenv would expand when the service reads its .env; "
                "change the value"
            )

    for rule in spec.require:
        if all(resolved.values.get(k) == v for k, v in rule.when.items()) and not resolved.values.get(rule.key):
            condition = ", ".join(f"{k}={v}" for k, v in rule.when.items())
            resolved.errors.append(
                f"{name}: {rule.key} is required" + (f" when {condition}" if condition else "") + f"; {how_to_set(rule.key)}"
            )
    return resolved
